// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2PXvOmpMYzHcF7nnS_6xx9HA-ngew9R8',
    appId: '1:101797689503:web:21f6d69e54bf469d92caaa',
    messagingSenderId: '101797689503',
    projectId: 'second-test-6e658',
    authDomain: 'second-test-6e658.firebaseapp.com',
    storageBucket: 'second-test-6e658.appspot.com',
    measurementId: 'G-3MGF3GW613',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdSXcPyHNuQ_Twe7kbyhIr1Clq69qhklk',
    appId: '1:101797689503:android:b2e85486e2f7e8ca92caaa',
    messagingSenderId: '101797689503',
    projectId: 'second-test-6e658',
    storageBucket: 'second-test-6e658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJKLJ-jbJxdAHTVh1-yT75Cj1voYE8pJE',
    appId: '1:101797689503:ios:54b6ecd1f180d4f192caaa',
    messagingSenderId: '101797689503',
    projectId: 'second-test-6e658',
    storageBucket: 'second-test-6e658.appspot.com',
    iosClientId: '101797689503-9e8s6jc3nesffcbd9rs0eadri4reltka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJKLJ-jbJxdAHTVh1-yT75Cj1voYE8pJE',
    appId: '1:101797689503:ios:54b6ecd1f180d4f192caaa',
    messagingSenderId: '101797689503',
    projectId: 'second-test-6e658',
    storageBucket: 'second-test-6e658.appspot.com',
    iosClientId: '101797689503-9e8s6jc3nesffcbd9rs0eadri4reltka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
